np.vstack

In [7]:
import numpy as np

In [8]:
rchannel = np.array([i for i in range(8)], dtype=np.uint8)
gchannel = np.array([i for i in range(8)], dtype=np.uint8)
bchannel = np.array([i for i in range(8)], dtype=np.uint8)

In [9]:
rgblist = np.array(rchannel)
rgblist = np.vstack((rgblist, gchannel, bchannel), dtype=np.double)


In [10]:
rgblist

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [16]:
colorlist = np.array([[1, 2, 3],[3, 4, 5]])
print(colorlist.shape[0])
colorlist[0]

2


array([1, 2, 3])

In [19]:
color = colorlist[0]
color

array([1, 2, 3])

In [21]:
data1 = (color[0], color[1], color[2])
data2 = (0, 0, 222)

In [12]:
import cv2
import numpy as np

In [13]:
img = np.zeros((500, 500, 3), np.uint8)
color = (0, 0, 255) # BGR
cv2.rectangle(img, (100,100), (500,500), color, -1)

cv2.imshow('rect', img)
cv2.waitKey(0)
cv2.destroyAllWindows()