np.vstack

In [1]:
import numpy as np
import cv2
from sklearn.cluster import KMeans

In [4]:
img = cv2.imread("test.png")
img

array([[[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       ...,

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]]

In [5]:
real = [10, 11, 12]
[h, w, span] = real
h

10

In [7]:
img = np.full((10, 10, 3), 255)
img

TypeError: full() missing 1 required positional argument: 'fill_value'

In [ ]:
rchannel = img[:,:,0].flatten()
gchannel = img[:,:,1].flatten()
bchannel = img[:,:,2].flatten()

# print(rchannel)
print(rchannel)

In [36]:
rgblist = np.array(rchannel)
rgblist = np.vstack((rgblist, gchannel, bchannel), dtype=np.double)
print(rgblist.shape)
rgblist.T


(3, 3200)


array([[255.,   0.,   0.],
       [255.,   0.,   0.],
       [255.,   0.,   0.],
       ...,
       [255.,   0.,   0.],
       [255.,   0.,   0.],
       [255.,   0.,   0.]])

In [41]:
kmeans = KMeans(n_clusters=3, max_iter=300, algorithm='auto')
kmeans.fit(rgblist.T)

c = kmeans.cluster_centers_
c

e:\Anaconda3\envs\qt\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
e:\Anaconda3\envs\qt\lib\site-packages\sklearn\cluster\_kmeans.py:1366: FutureWarning: algorithm='auto' is deprecated, it will be removed in 1.3. Using 'lloyd' instead.
  warnings.warn(
C:\Users\20709\AppData\Local\Temp\ipykernel_5156\1777636795.py:2: ConvergenceWarning: Number of distinct clusters (1) found smaller than n_clusters (3). Possibly due to duplicate points in X.
  kmeans.fit(rgblist.T)


array([[255.,   0.,   0.],
       [255.,   0.,   0.],
       [255.,   0.,   0.]])

In [13]:
img = np.zeros((500, 500, 3), np.uint8)
color = (0, 0, 255) # BGR
cv2.rectangle(img, (100,100), (500,500), color, -1)

cv2.imshow('rect', img)
cv2.waitKey(0)
cv2.destroyAllWindows()